import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      {/* 1. Apply background color directly to body so there are no empty gaps */}
      <body className="bg-stone-50 text-slate-800 font-sans antialiased">
        
        <div className="flex min-h-screen w-full">
          <Navbar />
          
          {/* 2. pl-20 offsets the Navbar. flex & justify-center perfectly centers your Landing page inside the remaining space */}
          <main className="flex-1 pl-20 flex justify-center">
            <div className="w-full max-w-6xl">
              {children}
            </div>
          </main>
          
        </div>
        
      </body>
    </html>
  );
}
