import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-stone-50 text-slate-800 font-sans antialiased overflow-x-hidden">
        
        <div className="flex min-h-screen w-full">
          <Navbar />
          
          {/* FIX 1: Added 'ml-20' here to strictly shift the entire page 80px away from the fixed sidebar.
            FIX 2: Changed padding to 'pl-4 md:pl-12 pr-0' so the right edge can go completely edge-to-edge.
          */}
          <main className="flex-1 ml-20 pl-4 md:pl-12 py-8 pr-0 w-full">
            
            {/* FIX 3: Removed 'max-w-6xl' and 'pl-20' here. 
              This lets your landing hero section expand across the entire rest of the website row!
            */}
            <div className="w-full">
              {children}
            </div>
            
          </main>
          
        </div>
        
      </body>
    </html>
  );
}
